### ISSUE TITLE
"HTTPError: HTTP Error 403: Forbidden"

### ISSUE THREAD

**Issue by immartian** [tradingeconomics/notebooks#3]
I was running the examples here with, `te.login('jupyter:jupyter')`, offered by the files. 
However, I received "HTTPError: HTTP Error 403: Forbidden" within Google Colab. I wonder what's the proper setting of credentials to run up these examples, or any other ways to test it ou?

**Comment by tatmush** [comment]
Signup for a free API key at https://developer.tradingeconomics.com/
